### ISSUE TITLE
deDE Translation (ToDo)

### ISSUE THREAD

**Issue by D3thw0lf** [KaefGAMES/StreamManager-Language#1]
- [ ] Settings Window
 - [ ] Default Settings (Page) 
 - [ ] Design Settings (Page)
 - [ ] GiveMEaway Settings (Page)
 - [ ] Chatbot Settings (Page)
 - [ ] SpotifyNOW Settings (Page)
- [ ] StreamAdmin
