### ISSUE TITLE
enUS Translation (ToDo)

### ISSUE THREAD

**Issue by D3thw0lf** [KaefGAMES/StreamManager-Language#2]
- [ ] Settings Window
  - [ ] Default Settings (Page) 
  - [ ] Design Settings (Page)
  - [ ] GiveMEaway Settings (Page)
  - [ ] Chatbot Settings (Page)
  - [ ] SpotifyNOW Settings (Page)
- [ ] StreamAdmin

(Mabe should get checked!)

**Comment by D3thw0lf** [comment]
Translation should get checked for spelling issues etc.
